import { Team, Player, Scenario } from './types';

// Player rosters with realistic career records and attribute profiles
export const SQUADS: Record<string, Player[]> = {
  CSK: [
    {
      id: 'csk_gaikwad',
      name: 'Ruturaj Gaikwad',
      role: 'Batsman',
      battingStyle: 'Right-hand',
      matches: 62,
      runs: 2380,
      avg: 41.7,
      sr: 137.5,
      highScore: 101,
      wickets: 0,
      form: [42, 60, 15, 88, 35],
      strengths: ['Elegant Covers Drive', 'Spin Manipulation', 'Timing'],
      weaknesses: ['Left-Arm Inswing', 'Early Outswingers']
    },
    {
      id: 'csk_dhoni',
      name: 'MS Dhoni',
      role: 'Wicketkeeper',
      battingStyle: 'Right-hand',
      matches: 258,
      runs: 5240,
      avg: 39.2,
      sr: 138.8,
      highScore: 84,
      wickets: 0,
      form: [28, 12, 19, 37, 2],
      strengths: ['Death Over Slog', 'Ice-cold Finishing', 'Helicopter Shot'],
      weaknesses: ['Spin Leg-Break', 'Slow Off-Breaks']
    },
    {
      id: 'csk_jadeja',
      name: 'Ravindra Jadeja',
      role: 'All-Rounder',
      battingStyle: 'Left-hand',
      bowlingStyle: 'Slow Left-Arm Orthodox',
      matches: 230,
      runs: 2890,
      avg: 26.5,
      sr: 129.2,
      highScore: 62,
      wickets: 156,
      bowlAvg: 30.1,
      economy: 7.6,
      bestBowling: '5/16',
      form: [15, 34, 12, 45, 8],
      strengths: ['Accurate Line & Length', 'Pull Shot', 'Exceptional Agility'],
      weaknesses: ['High Bouncer', 'Outside Off Channel']
    },
    {
      id: 'csk_dube',
      name: 'Shivam Dube',
      role: 'Batsman',
      battingStyle: 'Left-hand',
      bowlingStyle: 'Right-arm Medium',
      matches: 55,
      runs: 1320,
      avg: 29.3,
      sr: 145.4,
      highScore: 95,
      wickets: 5,
      form: [55, 12, 41, 66, 20],
      strengths: ['Monster Spin-Hitting', 'Straight Bowling Loft', 'Power'],
      weaknesses: ['High Express Pace', 'Outside Off-Stump Yorker']
    },
    {
      id: 'csk_pathirana',
      name: 'Matheesha Pathirana',
      role: 'Bowler',
      battingStyle: 'Right-hand',
      bowlingStyle: 'Right-arm Fast Slingshot',
      matches: 24,
      runs: 10,
      avg: 5.0,
      sr: 80.0,
      highScore: 4,
      wickets: 42,
      bowlAvg: 19.5,
      economy: 7.9,
      bestBowling: '4/15',
      form: [2, 3, 1, 0, 4], // wickets in last matches
      strengths: ['Slinging Yorker', 'Slower Dippers', 'Unorthodox Action'],
      weaknesses: ['Control/Wides', 'Initial Over Leakage']
    }
  ],
  MI: [
    {
      id: 'mi_rohit',
      name: 'Rohit Sharma',
      role: 'Batsman',
      battingStyle: 'Right-hand',
      matches: 250,
      runs: 6520,
      avg: 29.8,
      sr: 131.2,
      highScore: 109,
      wickets: 15,
      form: [64, 11, 40, 105, 5],
      strengths: ['Iconic Pull Shot', 'Powerplay Lofts', 'Class Timing'],
      weaknesses: ['Left-Arm Swinger Inwards', 'Leg-spin Googly']
    },
    {
      id: 'mi_sky',
      name: 'Suryakumar Yadav',
      role: 'Batsman',
      battingStyle: 'Right-hand',
      matches: 145,
      runs: 3540,
      avg: 31.6,
      sr: 143.5,
      highScore: 103,
      wickets: 0,
      form: [52, 78, 102, 6, 45],
      strengths: ['360-Degree Sweep', 'Incredible Wristwork', 'Behind-Square Flick'],
      weaknesses: ['Slow Wide Rollers', 'Subtle Sliders']
    },
    {
      id: 'mi_hardik',
      name: 'Hardik Pandya',
      role: 'All-Rounder',
      battingStyle: 'Right-hand',
      bowlingStyle: 'Right-arm Fast Medium',
      matches: 138,
      runs: 2450,
      avg: 28.5,
      sr: 145.8,
      highScore: 91,
      wickets: 64,
      bowlAvg: 33.2,
      economy: 8.8,
      bestBowling: '3/20',
      form: [21, 14, 45, 12, 39],
      strengths: ['Hard-Hitting Off-Drive', 'Heavy Fast Short-Ball', 'Power Finish'],
      weaknesses: ['Tight Wide Yorker', 'Sharp Inward Cutter']
    },
    {
      id: 'mi_bumrah',
      name: 'Jasprit Bumrah',
      role: 'Bowler',
      battingStyle: 'Right-hand',
      bowlingStyle: 'Right-arm Fast Hyperextended',
      matches: 132,
      runs: 85,
      avg: 10.6,
      sr: 98.4,
      highScore: 16,
      wickets: 162,
      bowlAvg: 22.8,
      economy: 7.3,
      bestBowling: '5/10',
      form: [3, 2, 4, 1, 2],
      strengths: ['Stifling Toe-Crushing Yorker', 'Slower Off-Cutter', 'Uncanny Release'],
      weaknesses: ['Tail-End Slogging runs']
    },
    {
      id: 'mi_tilak',
      name: 'Tilak Varma',
      role: 'Batsman',
      battingStyle: 'Left-hand',
      matches: 32,
      runs: 980,
      avg: 38.6,
      sr: 141.2,
      highScore: 84,
      wickets: 3,
      form: [34, 48, 51, 8, 22],
      strengths: ['Versatile Sweep', 'Aggressive Loft', 'Calm Pressure Solver'],
      weaknesses: ['Spin Sliders', 'Express Bouncer']
    }
  ],
  RCB: [
    {
      id: 'rcb_kohli',
      name: 'Virat Kohli',
      role: 'Batsman',
      battingStyle: 'Right-hand',
      matches: 244,
      runs: 7650,
      avg: 38.4,
      sr: 130.5,
      highScore: 113,
      wickets: 4,
      form: [18, 92, 51, 70, 113],
      strengths: ['Anchor Accumulator', 'Immaculate Cover Drive', 'Chasing Pressure Master'],
      weaknesses: ['Fifth-Stump Outswinger', 'Left-Arm Spin Drag']
    },
    {
      id: 'rcb_faf',
      name: 'Faf du Plessis',
      role: 'Batsman',
      battingStyle: 'Right-hand',
      matches: 138,
      runs: 4320,
      avg: 36.9,
      sr: 134.2,
      highScore: 96,
      wickets: 0,
      form: [14, 44, 78, 2, 53],
      strengths: ['Fast Hand Loft', 'Pace Acceleration', 'Exceptional Boundaries fielding'],
      weaknesses: ['Inward Quick Nip-Backers', 'Slow Off-Breaks']
    },
    {
      id: 'rcb_maxwell',
      name: 'Glenn Maxwell',
      role: 'All-Rounder',
      battingStyle: 'Right-hand',
      bowlingStyle: 'Right-arm Off-Spin',
      matches: 125,
      runs: 2750,
      avg: 25.2,
      sr: 156.8,
      highScore: 103,
      wickets: 38,
      bowlAvg: 31.8,
      economy: 8.3,
      bestBowling: '3/15',
      form: [1, 28, 4, 76, 12],
      strengths: ['Unorthodox Reverse Sweep', 'Fearsome Power Slog', 'Match Winner'],
      weaknesses: ['Express Outswinging Bouncer', 'Early Trapped LBW']
    },
    {
      id: 'rcb_karthik',
      name: 'Dinesh Karthik',
      role: 'Wicketkeeper',
      battingStyle: 'Right-hand',
      matches: 246,
      runs: 4820,
      avg: 26.8,
      sr: 135.4,
      highScore: 97,
      wickets: 0,
      form: [35, 1, 24, 53, 0],
      strengths: ['Slick Lap Sweep', 'Pocket Dynamo Punch', 'End Over Finisher'],
      weaknesses: ['Hard Leg-Spin Googly', 'High Outstretching Pace']
    },
    {
      id: 'rcb_siraj',
      name: 'Mohammed Siraj',
      role: 'Bowler',
      battingStyle: 'Right-hand',
      bowlingStyle: 'Right-arm Fast Outswing',
      matches: 88,
      runs: 102,
      avg: 8.5,
      sr: 90.0,
      highScore: 14,
      wickets: 98,
      bowlAvg: 29.5,
      economy: 8.5,
      bestBowling: '4/21',
      form: [1, 3, 0, 2, 1],
      strengths: ['Fierce Seams Wobble', 'Early Powerplay Outswinger', 'High Intent'],
      weaknesses: ['Death Over Flatters', 'Slightly Erratic Lengths']
    }
  ],
  SRH: [
    {
      id: 'srh_head',
      name: 'Travis Head',
      role: 'Batsman',
      battingStyle: 'Left-hand',
      bowlingStyle: 'Right-arm Off-Spin',
      matches: 31,
      runs: 1120,
      avg: 36.1,
      sr: 168.2,
      highScore: 102,
      wickets: 2,
      form: [89, 41, 102, 11, 56],
      strengths: ['Fierce Square Slash', 'Fearsome Powerplay Carnage', 'Pace Smash'],
      weaknesses: ['Left-Arm Orthodox Spin', 'Tight Slanting-In Body Bouncers']
    },
    {
      id: 'srh_klaasen',
      name: 'Heinrich Klaasen',
      role: 'Wicketkeeper',
      battingStyle: 'Right-hand',
      matches: 38,
      runs: 1240,
      avg: 41.3,
      sr: 172.4,
      highScore: 104,
      wickets: 0,
      form: [48, 67, 12, 80, 31],
      strengths: ['Monstrous Backfoot Pulls', 'Impenetrable Spin Countering', 'High Slog-Sweep'],
      weaknesses: ['Slanting Swing Off-Side Channel', 'Toe-Crushing Yorker']
    },
    {
      id: 'srh_abhishek',
      name: 'Abhishek Sharma',
      role: 'Batsman',
      battingStyle: 'Left-hand',
      bowlingStyle: 'Slow Left-Arm Orthodox',
      matches: 52,
      runs: 1380,
      avg: 27.6,
      sr: 154.2,
      highScore: 75,
      wickets: 9,
      form: [12, 75, 46, 101, 34],
      strengths: ['Powerplay Pulling Loft', 'Spin Smashing', 'Dynamic Left-hand Flow'],
      weaknesses: ['Hard Bouncer', 'Tighter Outswing Link']
    },
    {
      id: 'srh_cummins',
      name: 'Pat Cummins',
      role: 'Bowler',
      battingStyle: 'Right-hand',
      bowlingStyle: 'Right-arm Fast Hard-Length',
      matches: 58,
      runs: 540,
      avg: 18.2,
      sr: 148.5,
      highScore: 56,
      wickets: 62,
      bowlAvg: 28.6,
      economy: 8.5,
      bestBowling: '4/12',
      form: [2, 1, 3, 0, 1],
      strengths: ['Rifle Hard Lengths', 'Match Tactics Mastermind', 'Pace Cutters'],
      weaknesses: ['Extreme Fine Sweep', 'Flick off Pads']
    },
    {
      id: 'srh_natarajan',
      name: 'T. Natarajan',
      role: 'Bowler',
      battingStyle: 'Left-hand',
      bowlingStyle: 'Left-arm Fast Medium Yorker',
      matches: 51,
      runs: 12,
      avg: 4.0,
      sr: 50.0,
      highScore: 3,
      wickets: 68,
      bowlAvg: 26.5,
      economy: 8.4,
      bestBowling: '3/10',
      form: [2, 2, 1, 3, 0],
      strengths: ['Pinpoint Yorker', 'Slower Cutter Variation', 'Late Inswing Angle'],
      weaknesses: ['Powerplay Lofts', 'Right-arm Over Slog']
    }
  ]
};

// Complete Franchise Giant Team configurations
export const TEAMS: Record<string, Team> = {
  CSK: {
    code: 'CSK',
    name: 'Super Kings',
    fullName: 'Chennai Super Kings',
    primaryColor: '#FFD500', // Luminous Gold
    secondaryColor: '#FF9E00',
    textColor: '#101524',
    logo: '👑',
    squad: SQUADS.CSK
  },
  MI: {
    code: 'MI',
    name: 'Indians',
    fullName: 'Mumbai Indians',
    primaryColor: '#004BA0', // Cobalt Royal
    secondaryColor: '#00E5FF',
    textColor: '#FFFFFF',
    logo: '⚡',
    squad: SQUADS.MI
  },
  RCB: {
    code: 'RCB',
    name: 'Royal Challengers',
    fullName: 'Royal Challengers Bengaluru',
    primaryColor: '#E21D24', // Crimson Bold
    secondaryColor: '#D1AC3E',
    textColor: '#FFFFFF',
    logo: '🦁',
    squad: SQUADS.RCB
  },
  SRH: {
    code: 'SRH',
    name: 'Sunrisers',
    fullName: 'Sunrisers Hyderabad',
    primaryColor: '#FF3E15', // Luminous Orange
    secondaryColor: '#FF7C15',
    textColor: '#FFFFFF',
    logo: '🧡',
    squad: SQUADS.SRH
  }
};

// Preset Scenarios defining highly engaging live situations matching the requested structure
export const SCENARIOS: Scenario[] = [
  {
    id: 'scenario_dhoni_climax',
    title: 'Dhoni Last Over Miracle',
    phase: 'Death Overs',
    battingTeamCode: 'CSK',
    bowlingTeamCode: 'MI',
    innings: 2,
    score: 169,
    wickets: 6,
    overs: 19,
    ballsInOver: 0,
    target: 187, // Needs 18 off 6 balls
    strikerId: 'csk_dhoni',
    nonStrikerId: 'csk_jadeja',
    bowlerId: 'mi_bumrah',
    strikerRuns: 12,
    strikerBalls: 5,
    nonStrikerRuns: 15,
    nonStrikerBalls: 12,
    bowlerWickets: 2,
    bowlerRuns: 24,
    bowlerOvers: 3.0,
    description: 'The ultimate El Clásico finishes in a white-hot environment! Chennai requires 18 runs off the final 6 balls to secure victory. MS Dhoni is on strike; Jasprit Bumrah has the leather hand. Maximum broadcast tension.'
  },
  {
    id: 'scenario_sky_absolute_carnage',
    title: 'SKY 360° Demolition',
    phase: 'Middle Overs',
    battingTeamCode: 'MI',
    bowlingTeamCode: 'RCB',
    innings: 1,
    score: 122,
    wickets: 3,
    overs: 12,
    ballsInOver: 3,
    strikerId: 'mi_sky',
    nonStrikerId: 'mi_hardik',
    bowlerId: 'rcb_siraj',
    strikerRuns: 52,
    strikerBalls: 22,
    nonStrikerRuns: 8,
    nonStrikerBalls: 6,
    bowlerWickets: 1,
    bowlerRuns: 32,
    bowlerOvers: 2.3,
    description: 'Suryakumar Yadav has unleashed full mayhem, reaching his 50 in just 21 balls. He is batting in full 360-degree flow. Mohammed Siraj is hunting for defensive yorkers under immense pressure.'
  },
  {
    id: 'scenario_kohli_reconstruct',
    title: 'Kohli Chasing Anchor',
    phase: 'Powerplay',
    battingTeamCode: 'RCB',
    bowlingTeamCode: 'SRH',
    innings: 2,
    score: 32,
    wickets: 3,
    overs: 5,
    ballsInOver: 0,
    target: 205, // Chasing 205
    strikerId: 'rcb_kohli',
    nonStrikerId: 'rcb_maxwell',
    bowlerId: 'srh_cummins',
    strikerRuns: 18,
    strikerBalls: 12,
    nonStrikerRuns: 1,
    nonStrikerBalls: 2,
    bowlerWickets: 1,
    bowlerRuns: 8,
    bowlerOvers: 2.0,
    description: 'A devastating start for RCB chasing a daunting 205. They lie stranded at 32/3 in the 5th over. Virat "King" Kohli anchors the recovery next to Glenn Maxwell. Pat Cummins is operating with aggressive slip fields.'
  },
  {
    id: 'scenario_klaasen_death',
    title: 'Klaasen Late Ignition',
    phase: 'Death Overs',
    battingTeamCode: 'SRH',
    bowlingTeamCode: 'RCB',
    innings: 1,
    score: 215,
    wickets: 4,
    overs: 18,
    ballsInOver: 0,
    strikerId: 'srh_klaasen',
    nonStrikerId: 'srh_abhishek',
    bowlerId: 'rcb_siraj',
    strikerRuns: 48,
    strikerBalls: 16,
    nonStrikerRuns: 32,
    nonStrikerBalls: 15,
    bowlerWickets: 1,
    bowlerRuns: 45,
    bowlerOvers: 3.0,
    description: 'Heinrich Klaasen is rewriting the manual of spin and pace obliteration. SRH is 215/4 at the start of the 19th over. Bowler Mohammed Siraj is trying to curb Klaasen from pushing towards an unprecedented 240+.'
  }
];
